# Generated by Django 5.2.6 on 2025-09-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_exemplemodele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplemodele',
            name='chemin_fichier',
        ),
        migrations.RemoveField(
            model_name='exemplemodele',
            name='donnees_binaires',
        ),
        migrations.RemoveField(
            model_name='exemplemodele',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='exemplemodele',
            name='image',
        ),
    ]
